function GS_yyyymmdd = importGS(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GS_yyyymmdd = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  GS_yyyymmdd = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  GS_20201016 = importGS("GS_2020-10-16.csv", [9, 52]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Jun-2022 17:50:55

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [9, 52];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 15, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Method", "Statistic", "L6_0", "L6_075", "T_0", "T_05", "T_075", "L4_0", "L4_075", "L34_0", "L34_075", "S_0", "S_075", "SL_0", "SL_075"];
opts.VariableTypes = ["string", "string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Method", "Statistic"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Method", "Statistic"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["L6_0", "L6_075", "T_0", "T_05", "T_075", "L4_0", "L4_075", "L34_0", "L34_075", "S_0", "S_075", "SL_0", "SL_075"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["L6_0", "L6_075", "T_0", "T_05", "T_075", "L4_0", "L4_075", "L34_0", "L34_075", "S_0", "S_075", "SL_0", "SL_075"], "ThousandsSeparator", ",");

% Import the data
GS_yyyymmdd = readtable(filename, opts);

end