function xylemdata = importxylem(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  MRD01210925210929B = IMPORTFILE(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  MRD01210925210929B = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  MRD01210925210929B = IMPORTFILE(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  MRD01210925210929b = importxylem("C:\Users\4156366\OneDrive - Universiteit Utrecht\eurecca-wp2\data\water\processed\sedmex\xylem\MRD01-210925-210929b.xlsx", "MRD01-210925-210929b", [19, 601]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Jul-2022 15:59:02

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [19, 601];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 79);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":CA" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["RecordTime", "RecordNumber", "Var3", "InputVoltageV", "Var5", "InputVoltageAvgV", "Var7", "InputVoltageMinV", "Var9", "InputVoltageMaxV", "Var11", "CPUCoreActive", "Var13", "MemoryUsedBytes", "Var15", "InternalTemperatureDegC", "Var17", "GPSLatitudeDeg", "Var19", "GPSLongitudeDeg", "Var21", "Var22", "SignificantWaveHeightHm0m", "Var24", "WavePeakDirectionDegM", "Var26", "WavePeakDirectionSwellDegM", "Var28", "WaveMeanDirectionDegM", "Var30", "WavePeakDirectionWindDegM", "Var32", "WaveMeanPeriodTm02s", "Var34", "WavePeakPeriods", "Var36", "WavePeakPeriodSwells", "Var38", "WavePeakPeriodWinds", "Var40", "WaveHeightSwellHm0m", "Var42", "WaveHeightWindHm0m", "Var44", "WaveHeightHmaxm", "Var46", "WaveHeightCrestm", "Var48", "WaveHeightTroughm", "Var50", "WavePeriodTmaxs", "Var52", "WavePeriodTzs", "Var54", "SignificantWaveHeightH13m", "Var56", "MeanSpreadingAngleDegM", "Var58", "FirstOrderSpreadDegM", "Var60", "LongCrestednessParameters", "Var62", "HeadingDegM", "Var64", "PitchDeg", "Var66", "RollDeg", "Var68", "StDevHeadingDegM", "Var70", "StDevPitchDeg", "Var72", "StDevRollDeg", "Var74", "InputVoltageV1", "Var76", "InputCurrentmA", "Var78", "MemoryUsedBytes1"];
opts.SelectedVariableNames = ["RecordTime", "RecordNumber", "InputVoltageV", "InputVoltageAvgV", "InputVoltageMinV", "InputVoltageMaxV", "CPUCoreActive", "MemoryUsedBytes", "InternalTemperatureDegC", "GPSLatitudeDeg", "GPSLongitudeDeg", "SignificantWaveHeightHm0m", "WavePeakDirectionDegM", "WavePeakDirectionSwellDegM", "WaveMeanDirectionDegM", "WavePeakDirectionWindDegM", "WaveMeanPeriodTm02s", "WavePeakPeriods", "WavePeakPeriodSwells", "WavePeakPeriodWinds", "WaveHeightSwellHm0m", "WaveHeightWindHm0m", "WaveHeightHmaxm", "WaveHeightCrestm", "WaveHeightTroughm", "WavePeriodTmaxs", "WavePeriodTzs", "SignificantWaveHeightH13m", "MeanSpreadingAngleDegM", "FirstOrderSpreadDegM", "LongCrestednessParameters", "HeadingDegM", "PitchDeg", "RollDeg", "StDevHeadingDegM", "StDevPitchDeg", "StDevRollDeg", "InputVoltageV1", "InputCurrentmA", "MemoryUsedBytes1"];
opts.VariableTypes = ["datetime", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double", "char", "double"];

% Specify variable properties
opts = setvaropts(opts, ["Var3", "Var5", "Var7", "Var9", "Var11", "Var13", "Var15", "Var17", "Var19", "Var21", "Var22", "Var24", "Var26", "Var28", "Var30", "Var32", "Var34", "Var36", "Var38", "Var40", "Var42", "Var44", "Var46", "Var48", "Var50", "Var52", "Var54", "Var56", "Var58", "Var60", "Var62", "Var64", "Var66", "Var68", "Var70", "Var72", "Var74", "Var76", "Var78"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var3", "Var5", "Var7", "Var9", "Var11", "Var13", "Var15", "Var17", "Var19", "Var21", "Var22", "Var24", "Var26", "Var28", "Var30", "Var32", "Var34", "Var36", "Var38", "Var40", "Var42", "Var44", "Var46", "Var48", "Var50", "Var52", "Var54", "Var56", "Var58", "Var60", "Var62", "Var64", "Var66", "Var68", "Var70", "Var72", "Var74", "Var76", "Var78"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "RecordTime", "InputFormat", "");

% Import the data
xylemdata = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":CA" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    xylemdata = [xylemdata; tb]; %#ok<AGROW>
end

end